name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Netlify (Develop)
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEVELOP }}
      run: |
        echo "Deploying to Netlify (Develop)..."
        curl -X POST -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
             "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/builds"

    - name: Update Database (Develop)
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL_DEVELOP }}
      run: |
        echo "Running database migrations (Develop)..."
        npx prisma migrate deploy --schema=prisma/schema.prisma
