name: Deploy Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build HTML
      run: |
        mkdir -p dist
        cp index.html dist/index.html

    - name: Deploy to Netlify (Develop)
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEVELOP }}
      run: |
        npx netlify deploy --prod --dir=dist
    - name: Run Database Migrations (Develop)
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL_DEVELOP }}
      run: |
        npx prisma migrate deploy --schema=prisma/schema.prisma
